# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Ui_RecipeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecipeWindow(object):
    def setupUi(self, RecipeWindow):
        RecipeWindow.setObjectName("RecipeWindow")
        RecipeWindow.resize(650, 586)
        RecipeWindow.setMinimumSize(QtCore.QSize(650, 586))
        font = QtGui.QFont()
        font.setPointSize(11)
        RecipeWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(RecipeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.body = QtWidgets.QWidget()
        self.body.setGeometry(QtCore.QRect(0, 0, 650, 558))
        self.body.setObjectName("body")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_title = QtWidgets.QLabel(self.body)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_2.addWidget(self.lbl_title)
        self.images = QtWidgets.QHBoxLayout()
        self.images.setObjectName("images")
        self.verticalLayout_2.addLayout(self.images)
        self.table_ingr = QtWidgets.QTableWidget(self.body)
        self.table_ingr.setObjectName("table_ingr")
        self.table_ingr.setColumnCount(2)
        self.table_ingr.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_ingr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ingr.setHorizontalHeaderItem(1, item)
        self.table_ingr.horizontalHeader().setVisible(False)
        self.table_ingr.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.table_ingr)
        self.inp_desc = QTextEditFitText(self.body)
        self.inp_desc.setObjectName("inp_desc")
        self.verticalLayout_2.addWidget(self.inp_desc)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.body)
        self.verticalLayout.addWidget(self.scrollArea)
        RecipeWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(RecipeWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        RecipeWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_edit = QtWidgets.QAction(RecipeWindow)
        self.action_edit.setObjectName("action_edit")
        self.action_delete = QtWidgets.QAction(RecipeWindow)
        self.action_delete.setObjectName("action_delete")
        self.action_save = QtWidgets.QAction(RecipeWindow)
        self.action_save.setObjectName("action_save")
        self.toolBar.addAction(self.action_edit)
        self.toolBar.addAction(self.action_save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_delete)

        self.retranslateUi(RecipeWindow)
        QtCore.QMetaObject.connectSlotsByName(RecipeWindow)

    def retranslateUi(self, RecipeWindow):
        _translate = QtCore.QCoreApplication.translate
        RecipeWindow.setWindowTitle(_translate("RecipeWindow", "Название рецепта"))
        self.lbl_title.setText(_translate("RecipeWindow", "Название рецепта"))
        item = self.table_ingr.horizontalHeaderItem(0)
        item.setText(_translate("RecipeWindow", "Ингредиент"))
        item = self.table_ingr.horizontalHeaderItem(1)
        item.setText(_translate("RecipeWindow", "Количество"))
        self.toolBar.setWindowTitle(_translate("RecipeWindow", "toolBar"))
        self.action_edit.setText(_translate("RecipeWindow", "Редактировать"))
        self.action_delete.setText(_translate("RecipeWindow", "Удалить"))
        self.action_save.setText(_translate("RecipeWindow", "Сохранить как текст"))
from functions import QTextEditFitText
